### ISSUE TITLE
timeouts on windows

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc-webdav#5]
CI is failing due to timeouts for windows jobs: https://github.com/iterative/dvc-webdav/actions/runs/3086838959/jobs/4992792623

**Comment by pared** [comment]
I ran the tests on vagrant and my personal windows machine and in my case the tests are also very slow. We need to investigate if its possible to speed things up.

**Comment by dtrifiro** [comment]
This is related to us starting to pre-populate the cache dir with prefixes (see https://github.com/iterative/dvc-objects/pull/147).

From my testing: on windows each mkdir call takes 2 to 4s, resulting in `dvc.push` taking more than half an hour just to create all cache directories. 

I'm assuming this issue will go away once we have batching c.c. @efiop

**Comment by skshetry** [comment]
The test server that we use is based on `wsgiref`, which may be part of the problem. On webdav4, I use `cheroot` server, looking at the tests, it's much faster on Windows than Linux to my surprise.

**Comment by skshetry** [comment]
Even though this is solved by using a multithreaded web server, from the WebDAV fs point of view, it does not make sense to stress it and make 256 `mkdir`/`mkcol` calls. The tests, therefore, take more than 8 mins on Windows.
